# Generated by Django 4.0.4 on 2022-05-29 18:14

import WarehouseApp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CellStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Статус ячейки')),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя сотрудника')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Фамилия сотрудника')),
                ('last_name', models.CharField(max_length=25, verbose_name='Отчество сотрудника')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('password', models.CharField(max_length=25, verbose_name='Пароль')),
                ('begin_date', models.DateTimeField(verbose_name='Дата приема на работу')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('receiver_company', models.CharField(max_length=125, verbose_name='Кампания получатель')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('total_cost', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Конечная цена')),
                ('exp_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='GoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование группы товара')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Цена товара')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Объем товара')),
                ('icon', models.ImageField(upload_to=WarehouseApp.models.good_path)),
                ('specs', models.FileField(upload_to=WarehouseApp.models.good_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.category', verbose_name='Категория')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goodgroup', verbose_name='Группа')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.cell', verbose_name='Место на складе')),
            ],
        ),
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Отгружаемое количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отгрузки')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование позиции')),
                ('salary', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_day', models.DateTimeField()),
                ('receiver_company', models.CharField(max_length=125, verbose_name='Кампания получатель')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('total_cost', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Конечная цена')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods', verbose_name='Товар')),
                ('rec_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Тип секции')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование подкатегории')),
            ],
        ),
        migrations.CreateModel(
            name='SupGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Цена товара')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Объем товара')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goodgroup', verbose_name='Товарная группа')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=125, verbose_name='Наименованире кампании')),
                ('company_phone', models.CharField(max_length=12, verbose_name='Номер толефона')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('company_address', models.CharField(max_length=125, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата формирование поставки')),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Конечная цена')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник, сформировавший поставку')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='SupString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('cost', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Стоимость, в соответствии с количеством товара')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supgood', verbose_name='Товар поставки')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.supply')),
            ],
        ),
        migrations.AddField(
            model_name='supgood',
            name='supllier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='supgood',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.unit', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Наименование секции')),
                ('free_volume', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Свободный объем')),
                ('total_volume', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Общий объем')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.sectiontype', verbose_name='Тип секции')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_good_balance', models.IntegerField(verbose_name='Начальный остаток товара')),
                ('closing_good_balance', models.IntegerField(verbose_name='Конечный остаток товара')),
                ('expenditure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.expenditure', verbose_name='Доверенность')),
                ('receipts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts', verbose_name='Накладная')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_amount', models.IntegerField(verbose_name='Начальное количество товара')),
                ('receive_date', models.DateField(verbose_name='Дата поступления')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Дата реализации')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods')),
                ('loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.loading')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts')),
            ],
        ),
        migrations.AddField(
            model_name='receipts',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='goods',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='goods',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.unit', verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='GoodMoving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_from', models.CharField(max_length=250, verbose_name='Откуда')),
                ('place_to', models.CharField(max_length=250, verbose_name='Куда')),
                ('status', models.CharField(choices=[('ps', 'Well done'), ('ip', 'In progress')], max_length=2, verbose_name='Статус выполнения')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник')),
                ('good_moving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods', verbose_name='Перемещаемый товар')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='EmpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.report', verbose_name='Отчет')),
            ],
        ),
        migrations.AddField(
            model_name='emp',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.position', verbose_name='Наименование должности'),
        ),
        migrations.AddField(
            model_name='cell',
            name='cell_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.cellstatus', verbose_name='Статус ячейки'),
        ),
        migrations.AddField(
            model_name='cell',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.section', verbose_name='Наименование секции'),
        ),
    ]
