# Generated by Django 4.0.4 on 2022-05-29 19:21

import WarehouseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0002_alter_goods_specs_alter_receipts_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='icon',
            field=models.ImageField(max_length=500, upload_to=WarehouseApp.models.good_path),
        ),
    ]
