# Generated by Django 4.0.4 on 2022-05-30 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0003_alter_goods_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expenditure',
            name='good',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='good',
        ),
        migrations.RemoveField(
            model_name='report',
            name='closing_good_balance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='report',
            name='receipts',
        ),
        migrations.RemoveField(
            model_name='report',
            name='starting_good_balance',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата формирование отчета'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_good_balance', models.IntegerField(verbose_name='Начальный остаток товара')),
                ('closing_good_balance', models.IntegerField(verbose_name='Конечный остаток товара')),
                ('loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.loading', verbose_name='Отгрузка')),
                ('receipts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts', verbose_name='Накладная')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.report', verbose_name='Номер отчета')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supgood', verbose_name='Товар')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.receipts', verbose_name='Номер накладной')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество товара')),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.expenditure', verbose_name='Номер доверенности')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods', verbose_name='Товар')),
            ],
        ),
    ]
