# Generated by Django 4.0.4 on 2022-05-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0004_remove_expenditure_amount_remove_expenditure_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_status',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.cellstatus', verbose_name='Статус ячейки'),
        ),
        migrations.AlterField(
            model_name='goodmoving',
            name='status',
            field=models.CharField(choices=[('ps', 'Well done'), ('ip', 'In progress')], default='ip', max_length=2, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата формирование отчета'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата формирование поставки'),
        ),
    ]
