# Generated by Django 4.0.4 on 2022-05-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0005_alter_cell_cell_status_alter_goodmoving_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmoving',
            name='place_from',
        ),
        migrations.RemoveField(
            model_name='goodmoving',
            name='place_to',
        ),
        migrations.AddField(
            model_name='goodmoving',
            name='place_from_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_from_cell', to='WarehouseApp.cell', verbose_name='Откуда: ячейка'),
        ),
        migrations.AddField(
            model_name='goodmoving',
            name='place_from_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_from_section', to='WarehouseApp.section', verbose_name='Откуда: секция'),
        ),
        migrations.AddField(
            model_name='goodmoving',
            name='place_to_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_to_cell', to='WarehouseApp.cell', verbose_name='Куда: ячейка'),
        ),
        migrations.AddField(
            model_name='goodmoving',
            name='place_to_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_to_section', to='WarehouseApp.section', verbose_name='Куда: секция'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата формирования отчета'),
        ),
    ]
