# Generated by Django 4.0.4 on 2022-05-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0006_remove_goodmoving_place_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.supplier', verbose_name='Постащик'),
        ),
        migrations.AlterField(
            model_name='supstring',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.supply', verbose_name='Номер поставки'),
        ),
    ]
