# Generated by Django 4.0.4 on 2022-06-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0007_supply_supplier_alter_supstring_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Количество товара'),
            preserve_default=False,
        ),
    ]
