# Generated by Django 4.0.4 on 2022-06-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0008_goods_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='begin_date',
            new_name='date',
        ),
    ]
