# Generated by Django 4.0.4 on 2022-06-19 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0010_remove_expenditure_issue_date_expenditure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='taking_day',
        ),
        migrations.AddField(
            model_name='receipts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
            preserve_default=False,
        ),
    ]
