# Generated by Django 4.0.4 on 2022-06-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0011_remove_receipts_taking_day_receipts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supgood',
            old_name='supllier',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='empreport',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emps', to='WarehouseApp.emp', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='empreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='WarehouseApp.report', verbose_name='Отчет'),
        ),
    ]
