# Generated by Django 4.0.4 on 2022-06-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0012_rename_supllier_supgood_supplier_alter_empreport_emp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loading',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loading',
            name='good',
        ),
        migrations.AddField(
            model_name='reportstring',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods'),
        ),
        migrations.CreateModel(
            name='LoadingString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_amount', models.IntegerField(verbose_name='Отгружаемое количество товара')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods')),
                ('loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarehouseApp.loading', verbose_name='Номер отгрузки')),
            ],
        ),
    ]
