# Generated by Django 4.0.4 on 2022-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0013_remove_loading_amount_remove_loading_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='amount',
            field=models.IntegerField(verbose_name='Количество товара'),
        ),
    ]
