# Generated by Django 4.0.4 on 2022-06-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0014_alter_goods_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.emp', verbose_name='Сотрудник')),
                ('loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.loading', verbose_name='Отгрузка')),
            ],
        ),
    ]
