# Generated by Django 4.0.4 on 2022-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0015_emploading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supstring',
            name='cost',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Стоимость, в соответствии с количеством товара'),
        ),
    ]
