# Generated by Django 4.0.4 on 2022-06-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0017_alter_supply_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='loading_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отгружаемое количество'),
        ),
    ]
