# Generated by Django 4.0.4 on 2022-06-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0018_register_loading_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts'),
        ),
        migrations.AlterField(
            model_name='register',
            name='receive_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
    ]
