# Generated by Django 4.0.4 on 2022-06-23 15:22

import WarehouseApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0019_alter_register_receipt_alter_register_receive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='icon',
        ),
        migrations.AddField(
            model_name='goodgroup',
            name='icon',
            field=models.ImageField(default='C:\\JS\\WEBJS\\CourseWork\\Warehouse\\itemsIcons\\Компьютеры\\Комплектующие для ПК\\Видеокарты\\supplier_2_Palit GeForce GT 730 Silent LP\\author_not_found.png', max_length=500, upload_to=WarehouseApp.models.good_path),
        ),
        migrations.AlterField(
            model_name='register',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.goods', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='register',
            name='loading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.loading', verbose_name='Отгрузка'),
        ),
        migrations.AlterField(
            model_name='register',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts', verbose_name='Накладная'),
        ),
    ]
