# Generated by Django 4.0.4 on 2022-06-23 17:26

import WarehouseApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarehouseApp', '0020_remove_goods_icon_goodgroup_icon_alter_register_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Конечная цена'),
        ),
        migrations.AlterField(
            model_name='goodgroup',
            name='icon',
            field=models.ImageField(default='C:\\JS\\WEBJS\\CourseWork\\Warehouse\\itemsIcons\\Компьютеры\\Комплектующие для ПК\\Видеокарты\\supplier_2_Palit GeForce GT 730 Silent LP\\author_not_found.png', max_length=500, upload_to=WarehouseApp.models.good_path),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Конечная цена'),
        ),
        migrations.AlterField(
            model_name='register',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts', verbose_name='Доверенность'),
        ),
        migrations.AlterField(
            model_name='reportstring',
            name='receipts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WarehouseApp.receipts', verbose_name='Доверенность'),
        ),
    ]
