from django.contrib import admin
from WarehouseApp.models import *

# Register your models here.

admin.site.register(Unit)
admin.site.register(SectionType)
admin.site.register(GoodGroup)
admin.site.register(CellStatus)
admin.site.register(Position)
admin.site.register(Category)
admin.site.register(Subcategory)
admin.site.register(EmpReport)
admin.site.register(Goods)
admin.site.register(Cell)
admin.site.register(Section)
admin.site.register(Emp)
admin.site.register(Supplier)
admin.site.register(SupGood)
admin.site.register(Receipts)
admin.site.register(Expenditure)
admin.site.register(Report)
admin.site.register(Supply)
admin.site.register(SupString)
admin.site.register(GoodMoving)
admin.site.register(Register)
admin.site.register(Loading)
admin.site.register(ExpenditureString)
admin.site.register(ReceiptString)
admin.site.register(ReportString)